twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        version: '%env(VERSION)%'
        url_logo_pdf: '%env(URL_LOGO_PDF)%'
when@test:
    twig:
        strict_variables: true
