App\DTO\Usuario\RegistrarUsuarioDTO:
    properties:
        email:
            - NotBlank: 
                message: 'El campo email no puede quedar vacío.'
            - Email: 
                message: 'El campo email no tiene un formato correcto.'  
        password:
            - NotBlank: 
                message: 'El campo email no puede quedar vacío.'
